// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxbfzliqcfvluebyqynt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4YmZ6bGlxY2Z2bHVlYnlxeW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDUyNTgsImV4cCI6MjA2NTAyMTI1OH0.7IFEx5Hhtd1v58rp8TpqwZixREU0nACBw8h-8dA_QQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);